name: "DF415___attr-sep_knn_max-08_l1__shrink-none_no-bg__c-15_four-add__basic-bias__eik_01_lr_2e-4"
tag: "${rmspace:${data.prompt_library},_}"
exp_root_dir: "outputs_v3-1"
seed: 0

data_type: "multiview-multiprompt-multistep-datamodule-scene"
data:
  batch_size: 4 # should be the multiple of n_views
  n_view: 4 
  # 0-4999: 64x64, >=5000: 512x512
  # this drastically reduces VRAM usage as empty space is pruned in early training
  width: 256
  height: 256 # so high resolution !!
  ray_height: 64
  ray_width: 64
  # unsupervised data
  prompt_library: ???
  unsup_elevation_range: [0, 30]
  unsup_camera_distance_range: [0.8, 1.0] # relative
  unsup_fovy_range: [60, 60]
  relative_radius: true
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.
  n_val_views: 40
  n_test_views: 40
  # supervised data
  obj_library: "none"
  meta_json: "none"
  rgb_data_dir: "none"
  normal_data_dir: "none"
  depth_data_dir: "none"
  camera_data_dir: "none"
  frontal_idx: 24 # 24 is the frontal view
  # the sup / unsup ratio, for training
  sup_unsup_mode: "vanilla" # "vanilla"
  dim_gaussian: [1, 4, 64, 64] 
  pure_zeros: false
  # for training
  n_steps: ${system.num_parts_training}
  rays_d_normalize: true # required by GaussianSplatting

  guidance_processor_type: "dual-stable-diffusion-multi-prompt-processor-callable"
  guidance_processor:
    spawn: true
    pretrained_model_name_or_path: "pretrained/stable-diffusion-v1-5" # used by RichDreamer
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    pretrained_model_name_or_path_2nd: "pretrained/stable-diffusion-2-1-base" # used by MVDream, will be processed by condition_processor
    negative_prompt_2nd: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    use_local_text_embeddings: true

  condition_processor_type: "stable-diffusion-multi-prompt-processor-callable"
  condition_processor:
    spawn: true
    pretrained_model_name_or_path: ${system.geometry.space_generator_config.pretrained_model_name_or_path}
    negative_prompt: ""
    use_local_text_embeddings: true

system_type: "multiprompt-dual-renderer-multistep-generator-scene-system-v1"
system:
  initialize_shape: false # #true #
  visualize_samples: false 

  parallel_guidance: true

  # gradient_accumulation_steps: 2 # to replace the accumulate_grad_batches because it is not supported in our method

  # multi-step trianing / inference
  num_parts_training: 4 # TBD
  num_steps_training: 4 # TBD
  num_steps_sampling: 4
  noise_scheduler: "ddpm" 
  sample_scheduler: "ddim" 
  scheduler_dir: ${system.geometry.space_generator_config.pretrained_model_name_or_path}
  
  training_type: "rollout-rendering-distillation" # "progressive-rendering-distillation" or "rollout-rendering-distillation" or "rollout-rendering-distillation-last-step"

  geometry_type: "few-step-one-plane-stable-diffusion-v3"
  geometry:
    radius: 1. 

    # sdf bias related parameters
    sdf_bias: "sphere"
    sdf_bias_params: 0.5

    # knn related parameters
    knn_norm: 1 # 1: L1 distance; 2: L2 distance
    top_K: 8
    top_K_max: 8

    # activation functions
    # scaling_activation: "exp-0.1" # in # in ["exp-0.1", "sigmoid", "exp", "softplus"]
    # opacity_activation: "softplus" # in ["sigmoid-0.1", "sigmoid", "sigmoid-mipnerf", "softplus"]
    # color_activation: "sigmoid-mipnerf" # in ["scale_-11_01", "sigmoid-mipnerf"]
    position_activation: "none" # in ["none", "tanh"]
    
    # knn feature aggregation type
    pos_diff_interp_type: "fourier_add" # in ["num_mlp_concat", "num_mlp_add", "fourier_mlp_concat", "fourier_mlp_add", "fourier_concat", "fourier_add"]
    point_grad_shrink_point: false 
    point_grad_shrink_geo: false
    point_grad_shrink_tex: false

    # 3dgs attribute decoder heads
    primitive_decoder: 3dgs_attr-separate-tex" # in [None, "3dgs_attr-from-sdf", "3dgs_attr-from-feat", "3dgs_attr-separate-geo", "3dgs_attr-separate-tex"]

    
    # space generator related parameters
    space_generator_config:
      pretrained_model_name_or_path: "pretrained/stable-diffusion-2-1-base"
      training_type: "self_lora_rank_64-cross_lora_rank_64-locon_rank_64" 
      output_dim: 15 # must be the multiple of 6 plus 3
      # gradient_checkpoint: false


  material_type: no-material
  material:
    n_output_dims: 3
    requires_normal: true
    color_activation: sigmoid-mipnerf # follow OpenLRM


  background_type: "solid-color-background"
  background:
    color: [0.5, 0.5, 0.5]
    eval_color: [0.5, 0.5, 0.5]

  renderer_type: generative-space-3dgs-rasterize-renderer-v2

  renderer_2nd_type: generative_point_based_sdf_volume_renderer
  renderer_2nd:
    use_volsdf: false
    trainable_variance: false # important!
    learned_variance_init: 0.4605  # 0.4605 = log(100) / 10, 100 is the most common variance across the prompts
    
    rgb_grad_shrink: 1. #[0, 1, 0.01, 20000]

    estimator: importance
    num_samples_per_ray: 64
    num_samples_per_ray_importance: 128

    near_plane: 0.1
    far_plane: 4.0

  guidance_type: "richdreamer-mvdream-stablediffusion-asynchronous-score-distillation-guidance"
  guidance:

    # the following are specific to MV
    mv_min_step_percent: [0, 0.5, 0.02, 20000]
    mv_max_step_percent: 0.98
    mv_model_name_or_path: "sd-v2.1-base-4view"
    mv_ckpt_path: "pretrained/sd-v2.1-base-4view.pt" 
    mv_weight: 1.
    mv_guidance_scale: 20 #7.5
    mv_weighting_strategy: "dmd"

    # the following are specific to RD
    rd_min_step_percent: [0, 0.5, 0.02, 20000]
    rd_max_step_percent: 0.98
    rd_model_name_or_path: "nd-mv"
    rd_ckpt_path: "pretrained/nd_mv_ema.ckpt"
    rd_weight: 0.
    rd_guidance_scale: 20.
    rd_weighting_strategy: "dmd"
    cam_method: "rel_x2" # "", "rel" or ""

    rd_use_sds: false

    # the following are specific to SD
    sd_min_step_percent: [0, 0.5, 0.02, 20000]
    sd_max_step_percent: 0.98
    sd_model_name_or_path: "pretrained/stable-diffusion-2-1-base"
    sd_weight: 1.
    sd_guidance_scale: 5
    sd_weighting_strategy: "dmd"
    sd_oppo_side: true

    # the following are specific to ASD
    plus_schedule: "linear"

    # the following are specific to the combination of ASD with MV and SD
    mv_plus_random: true
    mv_plus_ratio: 0.
    rd_plus_random: true
    rd_plus_ratio: 0.
    sd_plus_random: true
    sd_plus_ratio: 0.

    # try to save memory cost
    gradient_checkpoint: true
    auto_grad: true

    eps: 0.1



  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    weighting_strategy: "v1" 

    # the loss for the first renderer
    lambda_asd: 1.
    lambda_eikonal: 0

    # the loss for the second renderer
    lambda_asd_2nd: 1.
    lambda_eikonal_2nd: 0.1

  optimizer:
    name: Adan # for fast convergence
    args:
      betas: [0.98, 0.92, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.0002 # 0.002
      # background:
      #   lr: 0.0002 # 0.002
      # renderer_2nd:
      #   lr: 0.0002 # 0.002



trainer:
  max_steps: 500000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  # val_check_interval: 2
  check_val_every_n_epoch: 5
  enable_progress_bar: true
  precision: 32
  strategy: "ddp"  #"ddp_find_unused_parameters_true" ##  # "deepspeed_stage_2"
  # accumulate_grad_batches: 1 # > 1 is not supported

checkpoint:
  save_last: true
  save_top_k: -1
  # every_n_train_steps: ${trainer.val_check_interval}
  every_n_epochs: ${trainer.check_val_every_n_epoch}
